Increase unit test coverage [SC3670]
maple-labs/proxy-factory pull request #10
Opened 2021-09-08 19:20 UTC by JGcarv

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog
## Function Signature Changes

## Features 

## Events

2021-09-08 21:13 UTC, deluca-mike commented on contracts/ProxyFactory.sol
> +        require(_implementation[version] != address(0), "PF:NI:NO_IMPLEMENTATION");
I don't think this is particularly needed, since `_initializeInstance` will fail if `_implementation[version] == address(0)`, but I guess it doesn't hurt.

2021-09-08 21:14 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    /*****+*********/
```suggestion
    /****************/
```

2021-09-08 21:24 UTC, deluca-mike requested changes
Also, would be nice to test a `uint8` in here, however, I guess an address is already a `uint160`, which does the job. However, perhaps then a bytes4. I don't recall if the casting of bytesX and uintX passing/trucating is from the same direction.

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    bytes32 private constant BYTES_SLOT   = 0x3333333333333333333333333333333333333333333333333333333333333333;
```suggestion
    bytes32 private constant ADDRESS_SLOT = 0x1111111111111111111111111111111111111111111111111111111111111111;
    bytes32 private constant BYTES32_SLOT = 0x2222222222222222222222222222222222222222222222222222222222222222;
    bytes32 private constant UINT256_SLOT = 0x3333333333333333333333333333333333333333333333333333333333333333;
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function setUintOf(uint256 key, uint256 value) external {
```suggestion
    function setUint256Of(uint256 key, uint256 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function setUintOf(uint256 key, address value) external {
```suggestion
    function setUint256Of(uint256 key, address value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function setUintOf(uint256 key, bytes32 value) external {
```suggestion
    function setUint256Of(uint256 key, bytes32 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function getUintIn(uint256 key) external view returns (uint256 value) {
```suggestion
    function getUint256In(uint256 key) external view returns (uint256 value) {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function getUintIn(address key) external view returns (uint256 value) {
```suggestion
    function getUint256In(address key) external view returns (uint256 value) {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function getUintIn(bytes32 key) external view returns (uint256 value) {
```suggestion
    function getUint256In(bytes32 key) external view returns (uint256 value) {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_set_and_retrieve_bytes32(bytes32 value) public {
```suggestion
    function test_setAndRetrieve_bytes32(bytes32 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_set_and_retrieve_uint(uint256 value) public {
```suggestion
    function test_setAndRetrieve_uint256(uint256 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_set_and_retrieve_address(address value) public {
```suggestion
    function test_setAndRetrieve_address(address value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_uint_to_uint(uint256 key, uint256 value) public {
```suggestion
    function test_referenceType_uint256ToUint256(uint256 key, uint256 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_uint_to_address(uint256 key, address value) public {
```suggestion
    function test_referenceType_uint256ToAddress(uint256 key, address value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_uint_to_bytes32(uint256 key, bytes32 value) public {
```suggestion
    function test_referenceType_uint256toBytes32(uint256 key, bytes32 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_address_to_uint(address key, uint256 value) public {
```suggestion
    function test_referenceType_addressToUint256(address key, uint256 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_address_to_address(address key, address value) public {
```suggestion
    function test_referenceType_addressToAddress(address key, address value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_address_to_bytes32(address key, bytes32 value) public {
```suggestion
    function test_referenceType_addressToBytes32(address key, bytes32 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_bytes32_to_uintss(bytes32 key, uint256 value) public {
```suggestion
    function test_referenceType_bytes32ToUint256(bytes32 key, uint256 value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_bytes32_to_address(bytes32 key, address value) public {
```suggestion
    function test_referenceType_bytes32ToAddress(bytes32 key, address value) external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    function test_referenceType_bytes32_to_bytes32(bytes32 key, bytes32 value) public {
```suggestion
    function test_referenceType_bytes32ToBytes32(bytes32 key, bytes32 value) **public** {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/Test.t.sol
> +
remove extra line

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/Test.t.sol
> +    function testFail_newInstance_nonRegistered_implementation() public {
```suggestion
    function testFail_newInstance_noRegisteredImplementation() external {
```

2021-09-08 21:24 UTC, deluca-mike commented on contracts/test/Test.t.sol
> +    function testFail_upgrade_nonRegistered_implementation() public {
```suggestion
    function testFail_upgrade_noRegisteredImplementation() external {
```

2021-09-09 13:24 UTC, JGcarv commented on contracts/ProxyFactory.sol
> +        require(_implementation[version] != address(0), "PF:NI:NO_IMPLEMENTATION");
The call will succeed with empty initialization arguments, creating a proxy with address(0) as implementation. Caught this with `testFail_newInstance_nonRegistered_implementation`

2021-09-09 17:53 UTC, lucas-manuel commented on contracts/test/SlotManipulatable.t.sol
> +    function getSlotValue(bytes32 slot) external view returns (bytes32 value){
`) {`

2021-09-09 21:08 UTC, deluca-mike requested changes
I think what @lucas-manuel and I meant was, remove all the `...AndReturnOld...` mock functions and tests, but leave the rest in, haha.

2021-09-09 21:08 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    bytes32 private constant REFERENCE_SLOT    = 0x1111111111111111111111111111111111111111111111111111111111111111;
```suggestion
    bytes32 private constant REFERENCE_SLOT = 0x1111111111111111111111111111111111111111111111111111111111111111;
```

2021-09-09 21:08 UTC, deluca-mike commented on contracts/test/SlotManipulatable.t.sol
> +    }
add a test for:
```
    function test_setAndRetrieve_bytes4(bytes4 value) external {
        storageContract.setSlotValue(bytes32(0), bytes32(value));

        assertEq(bytes4(storageContract.getSlotValue(bytes32(0))), value);
    }
```

2021-09-10 01:54 UTC, lucas-manuel requested changes

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/mocks/Mocks.sol
> -        uint256 arg = abi.decode(msg.data, (uint256));
We should keep this, as it shows how you can pass in args to a migration procedure

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(IMockImplementationV1(proxy).deltaOf(15), 2323);  // Should remain unchanged.
Remove comments

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(IMockImplementationV2(proxy).derbyOf(15), 2323);  // Should remain unchanged.
Update comments to add part about var name change

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(IMockImplementationV1(proxy).deltaOf(15), 2323);  // Should remain unchanged.
Remove comments

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +
Still need to do this

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(IMockImplementationV1(proxy).deltaOf(15), 2323);  // Should remain unchanged.
Remove comments

2021-09-10 01:54 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(IMockImplementationV2(proxy).derbyOf(15), 15);
This should use the arg

2021-09-10 12:48 UTC, JGcarv commented on contracts/test/mocks/Mocks.sol
> -        uint256 arg = abi.decode(msg.data, (uint256));
It's showing weirdly for me in the diff, but the arg is still present in `MockMigratorV1toV2`. I only removed in `MockMigratorV1toV2WithNoArgs`

2021-09-10 20:56 UTC, deluca-mike approved these changes
Minor cosmetic stuff, but I'm good with it.

2021-09-10 20:56 UTC, deluca-mike commented on contracts/test/Test.t.sol
> +        IMockImplementationV1 proxy = IMockImplementationV1(factory.newInstance(1, new bytes(0)));
Good catch!

2021-09-10 20:56 UTC, deluca-mike commented on contracts/test/Test.t.sol
> +        uint256 migrationArgument = 9090;
👍

2021-09-10 20:56 UTC, deluca-mike commented on contracts/test/Test.t.sol
> +        assertEq(IMockImplementationV2(proxy).derbyOf(15), 15);
Which arg?

2021-09-10 20:56 UTC, deluca-mike commented on contracts/test/mocks/Mocks.sol
> +contract MockImplementationV1 is IMockImplementationV1, Proxied {
Yup, yup, good catch.

2021-09-11 15:49 UTC, merged