refactor: Simpler, more functional, and less opinionated
maple-labs/proxy-factory pull request #7
Opened 2021-09-03 19:17 UTC by deluca-mike

- use correct ds-test
- use correct docker image for ci
- remove recommended version
- simplify implementation registration by treating an initializer exactly like a migrator
- create test account
- update tests and add test for new instance with no initializer and upgrade with no migrator
- prevent deleting migrator as opinionated layer
- removed all opinionated requires and moved non-opinionated requires to internals
- initializers are migrators to and from same version number, freeing up version 0, and resulting in less checks needed

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog
## Function Signature Changes

## Features 

## Events

2021-09-03 22:44 UTC, JGcarv commented
Yes! I like this structure way more!

2021-09-03 22:51 UTC, JGcarv submitted a review, later dismissed
I don't think changes are needed. This is looking good

2021-09-06 17:09 UTC, lucas-manuel requested changes

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(proxy.setDeltaOfAndReturnOldDeltaOf(2, 9292), 2929);
Add assertion for `deltaOf(2)`

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(proxy.setDeltaOfAndReturnOldDeltaOf(15, 7474), 6464);
Add assertion for `deltaOf(15)`

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
>          assertEq(proxy.implementation(), address(implementation));
In lines below add assertions after `setAndReturnOld` functions

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        MockV2            implementation = new MockV2();
I think itd be clearer if we named these contracts `MockImplementationV1` and `MockImplementationV2`

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
>          assertEq(proxy.implementation(), address(implementation));
Add assertions for `setAndReturnOld` functions

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
>          IMockV1(proxy2).setBeta(5959);
Add assertions for `setAndReturnOld` functions

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        user.proxyFactory_upgradeInstance(address(factory), proxy, 2, abi.encode(uint256(9090)));
Don't need to pass in args here since no migration is happening

2021-09-06 17:09 UTC, lucas-manuel commented on contracts/test/Test.t.sol
> +        assertEq(IMockV2(proxy).charlie(),   7575);  // is old beta
Sentence case comments

2021-09-08 01:40 UTC, lucas-manuel requested changes

2021-09-08 07:33 UTC, satyamakgec commented on contracts/Proxy.sol
> +    bytes32 private constant IMPLEMENTATION_SLOT = 0xf603533e14e17222e047634a2b3457fe346d27e294cedf9d21d74e5feea4a046;
I think the process get change here, We are keeping the implementation address in-house instead of querying from the factory? If yes then it will be hard to upgrade the proxy implementation if we don't have an explicit function to update the storage slot value with the new logic contract address.

2021-09-08 16:47 UTC, lucas-manuel approved these changes

2021-09-08 17:32 UTC, merged