Readme and License - SC3667
maple-labs/proxy-factory pull request #9
Opened 2021-09-08 18:28 UTC by JGcarv

# Description

# Integrations Checklist

- [ ] Have any function signatures changed? If yes, outline below.
- [ ] Have any features changed or been added? If yes, outline below.
- [ ] Have any events changed or been added? If yes, outline below.
- [ ] Has all documentation been updated?

# Changelog
## Function Signature Changes

## Features 

## Events

2021-09-08 21:05 UTC, deluca-mike requested changes

2021-09-08 21:05 UTC, deluca-mike commented on README.md
> +        function _registerImplementation(uint256 version, address implementationAddress) internal virtual returns (bool success)
```suggestion
        function _registerImplementation(uint256 version, address implementationAddress) internal virtual returns (bool success);
```
and the rest as well.

2021-09-09 13:09 UTC, deluca-mike submitted a review, later dismissed

2021-09-09 14:06 UTC, lucas-manuel requested changes
Still need to review the bottom, but here's the first sweep

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +        /// @dev Register a possible migration path and optionally sets a migrator contract
Register a migration path between versions and optionally set a migrator contract

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +        /// @dev Register a possible migration path and optionally sets a migrator contract
Registers

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +        /// @dev Register a new implementation address attached to a version, which can be used with any scheme of versioning.
Registers

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +        /// @dev Updates the implementation used by a proxy.
Proxy

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +The slim contract that is deployed. It saves both and `implementation` and the `factory` address to be able to execute transactions and upgrades.
The Proxy contract that is deployed and manages storage.

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +The slim contract that is deployed. It saves both and `implementation` and the `factory` address to be able to execute transactions and upgrades.
addresses

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +    /// @dev Storage slot with the address of the current factory. This is the keccak-256 hash of "IMPLEMENTATION_SLOT".
current implementation

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +    /// @dev Function to be called right after deployment, similar to a constructor in regular contracts.
Function to be called right after deployment, to set the `implementation` and the `factory` addresses in storage.

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +    /// @dev Function to delegatecall all incoming function to `implementation`
functions to the `implementation` address.

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +Helper contract that allow to manually modify storage that might be needed during a migration process
Helper contract that can manually modify storage when necessary (i.e., during a initialization/migration process)

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +    /// @dev returns the value stored at slot
Returns the value stored at the given slot.

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +    /// @dev set the storage slot to the given value
Sets the value stored at the given slot.

2021-09-09 14:06 UTC, lucas-manuel commented on README.md
> +    // @dev Get the storage slot for a reference type
Returns the storage slot for a reference type.

2021-09-09 14:51 UTC, JGcarv commented on README.md
> +        /// @dev Register a possible migration path and optionally sets a migrator contract
What's the correct form?

Register a migration path between versions and optionally set a migrator contract. 
or
Register a migration path between versions and optionally _sets_ a migrator contract

2021-09-09 16:07 UTC, lucas-manuel requested changes

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +```js
We almost shouldnt use `js` here since the highlighting doesn't seem to be working.

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +        /// @dev Deploys a new Proxy instance of and calls the initialization function with provided arguments.
instance and

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +        /// @dev Registers a migration path between versions and optionally set a migrator contract
sets

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +        /// @dev Registers a migration path between versions and optionally set a migrator contract
Add period

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +- To run a specific test function: `./test.sh <test_name>` (e.g. `./test.sh test_composability`)
`./test.sh -t <test_name>` (e.g. `./test.sh -t test_composability`)

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +
Single new line

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +
Single new line

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +The code is designed to be extended with needed feature, including access control and other guards on deployment and upgradeability, therefore it's not advised to use this as is. Additionally, it is
The code is designed to be highly flexible and extensible, meaning that logic that is usually part of these functions  (e.g., access controls) was not included. Therefore **it is strongly advised that these contracts be implemented with proper sanity checks, access controls and any extra logic necessary for security.**

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +The code is designed to be extended with needed feature, including access control and other guards on deployment and upgradeability, therefore it's not advised to use this as is. Additionally, it is
Lets also add our boilerplate disclaimer at the top of this README.

2021-09-09 16:07 UTC, lucas-manuel commented on README.md
> +
Single newline

2021-09-09 16:36 UTC, JGcarv commented on README.md
> +While there are other good libraries for base smart contracts, none of them satisfied the need to simultaneously be feature complete and allow to be used within our own style of development.
Which one? `While...development?`

2021-09-09 16:42 UTC, JGcarv commented on README.md
> +```js
I can remove, but I personally thinks that with no syntax highlighting at all it becomes harder to read.

2021-09-09 16:43 UTC, JGcarv commented on README.md
> +The code is designed to be extended with needed feature, including access control and other guards on deployment and upgradeability, therefore it's not advised to use this as is. Additionally, it is
Where can I find this disclaimer?

2021-09-09 20:20 UTC, merged